[package]
name = "halogen"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8", features = [
    "serde",
    "no-rng",
    "std",
], default-features = false }
monoio = { version = "0.2.3", features = [
    "zero-copy",
    "bytes",
    "iouring",
], optional = true, default-features = false }
flume = { version = "0.11", default-features = false, features = [
    "async",
    "nanorand",
], optional = true }
tracing = { version = "0.1", features = ["async-await"], optional = true }
serde = { version = "1", features = ["derive"] }
once_cell = { version = "1.19" }
futures-util = "0.3"
serde_json = { version = "1.0.116", optional = true }
simd-json = { version = "0.13.10", optional = true, features = ["known-key"] }

[features]
default = ["tracing", "monoio", "parking_lot", "flume", "serde_json"]
tracing = ["dep:tracing", "monoio?/tracing"]
monoio = ["dep:monoio"]
parking_lot = ["once_cell/parking_lot"]
flume = ["dep:flume", "monoio?/flume"]
serde_json = ["dep:serde_json"]
simd-json = ["dep:simd-json"]
