[package]
name = "halogen"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8", features = [
    "serde",
    "no-rng",
    "std",
], default-features = false }
tokio = { version = "1.37", features = [
    "macros",
    "io-std",
    "socket2",
    "sync",
    "test-util",
    "net",
], optional = true }

tracing = { version = "0.1", features = ["async-await"], optional = true }
serde = { version = "1", features = ["derive"] }
once_cell = { version = "1.19" }
futures-util = { version = "0.3", default-features = false, features = [
    "async-await",
    "std",
] }
serde_json = { version = "1.0", optional = true }
simd-json = { version = "0.13", optional = true, features = ["known-key"] }
async-net = { version = "2.0", optional = true }
async-io = { version = "2.3", optional = true }

[features]
default = ["tracing", "tokio", "simd-json"]

tracing = ["dep:tracing", "tokio?/tracing"]
parking_lot = ["once_cell/parking_lot", "tokio?/parking_lot"]

tokio = ["dep:tokio"]

serde_json = ["dep:serde_json"]
simd-json = ["dep:simd-json"]
async-lite = ["dep:async-net", "dep:async-io"]
