[package]
name = "halogen"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { workspace = true }
monoio = { workspace = true, optional = true }
flume = { workspace = true }
tracing = { workspace = true, optional = true }
futures-util = { workspace = true }

[features]
tracing = ["dep:tracing"]
monoio = ["dep:monoio"]
